### ISSUE TITLE
Errors popping on QUIT button

### ISSUE THREAD

**Issue by vineetjc** [vineetjc/pygame-Search-the-Key#19]
#5 adds restart and quit buttons but quit button gives:

```
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    search_key()
  File "main.py", line 256, in search_key
    show_end_screen()
  File "main.py", line 306, in show_end_screen
    windowSurface.blit(pygame.transform.scale(BG,(size)),(0,0))
pygame.error: display Surface quit

```

@divyang-mittal please confirm if this is an issue.

**Comment by vineetjc** [comment]
@divyang-mittal please fix since I believe you brought the changes, or anyone else can take it also

**Comment by vineetjc** [comment]
wrt #22 this is closed.
